"""create consultation_analysis table

Revision ID: 2af571154ca6
Revises: 
Create Date: 2026-03-24 20:57:17.390807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af571154ca6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_analysis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('detected_symptoms', sa.TEXT(), nullable=False),
    sa.Column('possible_conditions', sa.TEXT(), nullable=False),
    sa.Column('exams', sa.TEXT(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('mark_emergency', sa.Boolean(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultation_analysis')
    # ### end Alembic commands ###
