from enum import Enum

class USSDState(str, Enum):

    MAIN_MENU = "MAIN_MENU"

    REGISTER_FIRST_NAME = "REGISTER_FIRST_NAME"
    REGISTER_LAST_NAME = "REGISTER_LAST_NAME"
    REGISTER_EMAIL = "REGISTER_EMAIL"
    REGISTER_PIN = "REGISTER_PIN"
    REGISTER_CONFIRM_PIN = "REGISTER_CONFIRM_PIN"

    END = "END"
