from enum import Enum

class USSDState(str, Enum):

    MAIN_MENU = "MAIN_MENU"

    REGISTER_FIRST_NAME = "REGISTER_FIRST_NAME"
    REGISTER_LAST_NAME = "REGISTER_LAST_NAME"
    REGISTER_EMAIL = "REGISTER_EMAIL"
    REGISTER_PIN = "REGISTER_PIN"
    REGISTER_CONFIRM_PIN = "REGISTER_CONFIRM_PIN"

    END = "END"

class USSDPersonalInfo(str, Enum):

    MAIN_MENU = "PERSONAL_INFO"

    VERIFY_PIN = "PIN"
    COMPLETE_AGE = "REGISTER_AGE"
    COMPLETE_GENDER = "REGISTER_GENDER"
    COMPLETE_NATIONALITY = "REGISTER_NATIONALITY"
    COMPLETE_COUNTRY_OF_RESIDENCE = "REGISTER_COUNTRY_OF_RESIDENCE"
    COMPLETE_CITY_OF_RESIDENCE = "REGISTER_CITY_OF_RESIDENCE"
    COMPLETE_ADDRESS = "REGISTER_ADDRESS"
    COMPLETE_NEXT_KIN = "REGISTER_NEXT_KIN"
    COMPLETE_NEXT_KIN_RELATIONSHIP = "PATIENT_NEXT_KIN_RELATIONSHIP"
    COMPLETE_NEXT_KIN_PHONE_NUMBER = "PATIENT_NEXT_KIN_PHONE_NUMBER"
    COMPLETE_PREFERRED_LANGUAGE = "PATIENT_PREFERRED_LANGUAGE"
    
    END = "END"

class USSDMedicalInfo(str, Enum):
    """USSD For adding medical info"""
    MAIN_MENU = "MEDICAL_INFO"
    VERIFY_PIN = "PIN"
    BLOOD_TYPE = "ADD_BLOOD_TYPE"
    ALLERGIES = "ADD_ALLERGIES"
    CHRONIC_ILLNESS = "CHRONIC_ILLNESS"
    RECENT_VACCINATION = "RECENT_VACCINATIONS"

    END = "END"
